name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      
      - name: 'Install dependencies'
        run: npm ci
      
      - name: 'Run Tests'
        run: npm test
      
      - name: 'Coverage Comment'
        uses: MishaKav/jest-coverage-comment@v1
